language: octave

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# addons:
#   apt:
#     packages:
#       - mplayer

before_install:
  - managementtools/ci/travis_${TRAVIS_OS_NAME}

script:
  - cd Psychtoolbox
  - yes|octave --eval 'SetupPsychtoolbox.m'
