language: octave

os:
  - linux
#  - osx

cache:
  - apt

compiler:
  - gcc
#  - clang

env:
  global:
    - XVFB_OPTS="-screen 0 1024x768x24 -ac +extension GLX +render -noreset"

# addons:
#   apt:
#     packages:
#       - mplayer

before_install:
  - managementtools/ci/travis_${TRAVIS_OS_NAME}

script:
  - cd Psychtoolbox
  - yes| xvfb-run --auto-servernum --server-num=20 -s "$XVFB_OPTS" octave --eval 'SetupPsychtoolbox.m'
